
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - onecloud.yunion.io
  resources:
  - ansibleplaybooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - onecloud.yunion.io
  resources:
  - ansibleplaybooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - onecloud.yunion.io
  resources:
  - ansibleplaybooktemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - onecloud.yunion.io
  resources:
  - endpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - onecloud.yunion.io
  resources:
  - endpoints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - onecloud.yunion.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - onecloud.yunion.io
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
