apiVersion: onecloud.yunion.io/v1
kind: Endpoint
metadata:
  name: endpoint-sample
spec:
  regionId: region0
  name: test
  url:
    host:
      reference:
        kind: VirtualMachine
        namespace: onecloud
        name: ng-nihao
        fieldPath: Status.ExternalInfo.Ips[0]
    port: 8081
    prefix: test
